Jworthington/t 2213 implement existing api spec in the
tillit-dot-ai/two-documentation pull request #6
Opened 2021-12-15 14:56 UTC by JWorthington97

- removed admin / internal endpoints
- removed extraneous tags
- renamed all instances of Tillit to Two (except for Tillit AS)
- ordered operations alphabetically (through Redocly)
- created basic API landing page for Checkout API and Search API

2021-12-17 10:28 UTC, jkrgr commented on openapi/checkout-api.yaml
> +    post:
only get address should be in the spec

2021-12-17 10:45 UTC, jkrgr requested changes

2021-12-17 10:45 UTC, jkrgr commented on openapi/checkout-api.yaml
> +    post:
And that is the GET address with organization number (not with buyer id, and not with address id)

2021-12-17 10:45 UTC, jkrgr commented on openapi/checkout-api.yaml
> +        description: ID of the order
include the `lang` query parameter here for localization

2021-12-17 10:45 UTC, jkrgr commented on openapi/checkout-api.yaml
> +      description: Endpoint for creating a pdf invoice.
> Endpoint for downloading the invoice of a fulfilled order

2021-12-17 10:45 UTC, jkrgr commented on openapi/checkout-api.yaml
> +        Fulfilled requests should normally have empty request body.
> Set the order status to `FULFILLED`(similar to "capture" for cards). The invoice will be issued and distributed it to the customer.

2021-12-17 10:45 UTC, jkrgr commented on openapi/checkout-api.yaml
> +  /order_intent:
Could you go over the examples and update them to be more realistic?

2021-12-17 10:45 UTC, jkrgr commented on openapi/checkout-api.yaml
> +                    tracking_id: 18dc34e0-4045-4951-a00e-146856feacc6
`tracking_id` should be removed. If the response schema returns this we should remove it from the schema as well

2021-12-17 10:45 UTC, jkrgr commented on openapi/checkout-api.yaml
> +                    tracking_id: null
same here

2021-12-17 10:45 UTC, jkrgr commented on openapi/checkout-api.yaml
> +  '/order/{id}/verification':
internal endpoint, remove

2021-12-17 10:45 UTC, jkrgr commented on openapi/checkout-api.yaml
> +  '/orders/{id}/external_order_status':
private endpoint

2021-12-17 10:45 UTC, jkrgr commented on openapi/search-api.yaml
> +  '/search/company/address/{organization_number}':
yes, this is the only address endpoint we expose. then you can remove all the address endpoints in the other file

2021-12-17 10:45 UTC, jkrgr commented on openapi/search-api.yaml
> +  - url: 'http://localhost:3000'
Let's use the actual urls. Example requests:
Norway: https://no.search.two.inc/search?limit=50&offset=0&q=mono
UK: : https://gb.search.two.inc/search?limit=50&offset=0&q=mono

So our base urls differ between the countries. Not sure how to represent that in the open api spec, but should be a way

2021-12-17 10:45 UTC, jkrgr commented on openapi/search-api.yaml
> +        `GET https://search-api-demo-j6whfmualq-lz.a.run.app/search?limit=50&offset=0&q=monoz`
update the examples to use the proper urls

2021-12-20 10:49 UTC, JWorthington97 commented on openapi/checkout-api.yaml
> +                    tracking_id: 18dc34e0-4045-4951-a00e-146856feacc6
Removed from schema as well as here

2021-12-20 11:25 UTC, JWorthington97 commented on openapi/checkout-api.yaml
> +        description: ID of the order
@jkrgr I don't believe this is present in the checkout-api endpoint at the moment. Does it still need to be added?

2021-12-20 14:05 UTC, JWorthington97 commented
Also added authentication headers to endpoints that require it

2021-12-20 16:21 UTC, JWorthington97 commented
@jkrgr `Endpoint for accessing all orders made by a given merchant or buyer.` 

Is the get list of orders endpoint internal too? In checkout-api it requires AdminBasicAuth

2021-12-20 17:42 UTC, JWorthington97 commented
Updated all request / response examples with realistic data

2021-12-20 18:23 UTC, jkrgr commented on openapi/checkout-api.yaml
> +        description: ID of the order
It's present, and yes it should be included: check `invoice_pdf_handler`,  `?lang=en_US` and `?lang=nb_NO`. You also have `?v=original` to download the original invoice and not the credit note (if any)

2021-12-20 18:28 UTC, jkrgr commented
> @jkrgr Endpoint for accessing all orders made by a given merchant or buyer.
>Is the get list of orders endpoint internal too? In checkout-api it requires AdminBasicAuth

get orders by merchant or buyer (`retrieve_order_list_handler`) is `MerchantXApiKeyAuth` _or_ `AdminBasicAuth`. Note that url is `/v2/orders`. `retrieve_order_list_handler_legacy` should not be included.

2021-12-20 18:28 UTC, jkrgr approved these changes

2021-12-20 19:23 UTC, merged